src/main/kotlin/examples/maumau/view/GameScene.kt
src/main/kotlin/tools/aqua/bgw/elements/container/GameElementPoolView.kt

GameElementPoolView works as intended.

fix GameElementPoolView.kt

---

src/main/kotlin/examples/maumau/view/RefreshViewController.kt
src/main/kotlin/tools/aqua/bgw/core/MenuScene.kt
src/main/kotlin/tools/aqua/bgw/core/Scene.kt
src/main/kotlin/tools/aqua/bgw/elements/ElementView.kt
src/main/kotlin/tools/aqua/bgw/elements/gameelements/CardView.kt
src/main/kotlin/tools/aqua/bgw/elements/gameelements/DiceView.kt
src/main/kotlin/tools/aqua/bgw/observable/ObservableList.kt
src/main/kotlin/tools/aqua/bgw/visual/ColorVisual.kt
src/main/kotlin/tools/aqua/bgw/visual/CompoundVisual.kt
src/main/kotlin/tools/aqua/bgw/visual/ImageVisual.kt
src/main/kotlin/tools/aqua/bgw/visual/TextVisual.kt
src/main/kotlin/tools/aqua/bgw/visual/Visual.kt

Visual references bug

---

bgw-core/src/main/kotlin/tools/aqua/bgw/builder/UINodeBuilder.kt
bgw-core/src/main/kotlin/tools/aqua/bgw/components/uicomponents/Button.kt
bgw-core/src/main/kotlin/tools/aqua/bgw/components/uicomponents/CheckBox.kt
bgw-core/src/main/kotlin/tools/aqua/bgw/components/uicomponents/Label.kt
bgw-core/src/main/kotlin/tools/aqua/bgw/components/uicomponents/LabeledUIComponent.kt
bgw-core/src/main/kotlin/tools/aqua/bgw/components/uicomponents/TextArea.kt
bgw-core/src/main/kotlin/tools/aqua/bgw/components/uicomponents/TextField.kt
bgw-core/src/main/kotlin/tools/aqua/bgw/components/uicomponents/TextInputUIComponent.kt
bgw-core/src/main/kotlin/tools/aqua/bgw/components/uicomponents/UIComponent.kt

divides old LabeledUIComponent.kt into LabeledUIComponent.kt and TextInputUIComponent.kt
Button.kt, CheckBox.kt and Label.kt inherit from LabeledUIComponent.kt
TextArea.kt and TextField.kt inherit from TextInputUIComponent.kt
default alignment for all three LabeledUIComponent.kt inheritors is Alignment.CENTER
closes #116

implements alignment fields for LabeledUIComponent.kt

---

bgw-core/src/main/kotlin/tools/aqua/bgw/builder/VisualBuilder.kt
bgw-core/src/main/kotlin/tools/aqua/bgw/visual/ImageVisual.kt

- fixes minimal label width and height
- add a check for subimage dimensions

Multiple Visuals fixes

---

bgw-core/src/main/kotlin/tools/aqua/bgw/builder/UINodeBuilder.kt

Fixed font color not being applied to TableView.

---

bgw-core/src/main/kotlin/tools/aqua/bgw/builder/Frontend.kt

Fixed NullPointerException due to race condition in Frontend#sizeChanged

---

bgw-core/src/main/kotlin/tools/aqua/bgw/builder/FXConverters.kt

Fixed font family with whitespace bug. Closes #201

---

README.md
bgw-examples/bgw-tetris-example/build.gradle.kts
bgw-ui/build.gradle.kts

Upgraded JavaFX to version 17.0.2.

---

bgw-gui/src/main/kotlin/tools/aqua/bgw/builder/Frontend.kt

Disabled fade animation when switching between MenuScenes.

---

bgw-gui/src/main/kotlin/tools/aqua/bgw/builder/SceneBuilder.kt

New scene backgrounds not displayed correctly (#225)

---

bgw-docs/src/main/jekyll/components/uicomponents/uicomponents.md
bgw-gui/src/main/kotlin/tools/aqua/bgw/core/BoardGameApplication.kt
bgw-gui/src/main/kotlin/tools/aqua/bgw/core/Constants.kt
bgw-gui/src/main/kotlin/tools/aqua/bgw/util/Font.kt

 Add function to register ttf files

---

bgw-gui/src/main/kotlin/tools/aqua/bgw/builder/SceneBuilder.kt

Fix scene background lost on pane refresh.

---

bgw-gui/src/main/kotlin/tools/aqua/bgw/builder/LayoutNodeBuilder.kt

Fixed Grid not updated when dimensions of children changed causing reset of position.

---

bgw-gui/src/main/kotlin/tools/aqua/bgw/builder/NodeBuilder.kt
bgw-gui/src/main/kotlin/tools/aqua/bgw/builder/SceneBuilder.kt
bgw-gui/src/main/kotlin/tools/aqua/bgw/core/Scene.kt

Dragged elements can now be removed from parent in onDragDropped.

---

bgw-gui/src/main/kotlin/tools/aqua/bgw/builder/UINodeBuilder.kt
bgw-gui/src/main/kotlin/tools/aqua/bgw/components/uicomponents/BinaryStateButton.kt
bgw-gui/src/main/kotlin/tools/aqua/bgw/components/uicomponents/RadioButton.kt
bgw-gui/src/main/kotlin/tools/aqua/bgw/components/uicomponents/ToggleButton.kt

RadioButton and ToggleButton should now be able to contain Text to their right.
Font style (color, size, weight, style, etc.) and alignment should work.
isWraptext should work for ToggleButton.
Closing #223 .

Added text to RadioButton and ToggleButton.

---

bgw-net/bgw-net-client/src/main/kotlin/tools/aqua/bgw/net/client/BoardGameClient.kt
bgw-net/bgw-net-server/src/main/kotlin/tools/aqua/bgw/net/server/service/MessageService.kt

Fixed method invocation on client side.

Disabled json checking on server side.

---

bgw-examples/bgw-maumau-example/src/main/kotlin/tools/aqua/bgw/examples/maumau/view/scenes/MauMauGameScene.kt
bgw-gui/src/main/kotlin/tools/aqua/bgw/animation/MovementAnimation.kt

Added rotation of origin container stack to MovementAnimation.toComponentView calculation.

---

buildSrc/src/main/kotlin/tools/aqua/JekyllTasks.kt

Fixed jekyll build file permissions for docker on windows

---

bgw-net/bgw-net-client/src/main/kotlin/tools/aqua/bgw/net/client/BGWWebSocketClient.kt
bgw-net/bgw-net-client/src/main/kotlin/tools/aqua/bgw/net/client/BoardGameClient.kt
bgw-net/bgw-net-common/src/main/kotlin/tools/aqua/bgw/net/common/Constants.kt
bgw-net/bgw-net-common/src/main/kotlin/tools/aqua/bgw/net/common/request/CreateGameMessage.kt
bgw-net/bgw-net-server/src/main/kotlin/tools/aqua/bgw/net/server/entity/GameInstance.kt
bgw-net/bgw-net-server/src/main/kotlin/tools/aqua/bgw/net/server/service/GameService.kt
bgw-net/bgw-net-server/src/main/kotlin/tools/aqua/bgw/net/server/service/MessageService.kt
bgw-net/bgw-net-server/src/main/kotlin/tools/aqua/bgw/net/server/service/websocket/BGWHandshakeInterceptor.kt
bgw-net/bgw-net-server/src/main/kotlin/tools/aqua/bgw/net/server/service/websocket/BGWWebsocketHandler.kt
bgw-net/bgw-net-server/src/main/kotlin/tools/aqua/bgw/net/server/view/MainLayout.kt
bgw-net/bgw-net-server/src/main/kotlin/tools/aqua/bgw/net/server/view/NetworkSecretForm.kt

Changed route from /chat to /connect.
Renamed secret.

Added dedicated HTTP response codes for error types on handshake.

---

bgw-net/bgw-net-server/src/main/kotlin/tools/aqua/bgw/net/server/entity/tables/SchemasByGame.kt
bgw-net/bgw-net-server/src/main/kotlin/tools/aqua/bgw/net/server/entity/tables/SchemasByGameRepository.kt
bgw-net/bgw-net-server/src/main/kotlin/tools/aqua/bgw/net/server/service/oauth/CustomSuccessHandler.kt
bgw-net/bgw-net-server/src/main/kotlin/tools/aqua/bgw/net/server/view/ConnectionsView.kt
bgw-net/bgw-net-server/src/main/resources/.gitignore

Changed visible routes and added BGW-Net-Admins group.

---

bgw-net/bgw-net-server/src/main/kotlin/tools/aqua/bgw/net/server/service/websocket/BGWWebSocketConfigurer.kt

Added Network secret initialization.

---

bgw-gui/src/main/kotlin/tools/aqua/bgw/builder/NodeBuilder.kt
bgw-gui/src/main/kotlin/tools/aqua/bgw/builder/SceneBuilder.kt

Blocked keyboard inputs for components on BoardGameScene if MenuScene is currently shown.

---

bgw-net/bgw-net-client/src/main/kotlin/tools/aqua/bgw/net/client/BoardGameClient.kt
bgw-net/bgw-net-common/src/main/kotlin/tools/aqua/bgw/net/common/request/CreateGameMessage.kt
bgw-net/bgw-net-common/src/main/kotlin/tools/aqua/bgw/net/common/response/CreateGameResponse.kt
bgw-net/bgw-net-server/src/main/kotlin/tools/aqua/bgw/net/server/service/GameService.kt
bgw-net/bgw-net-server/src/main/kotlin/tools/aqua/bgw/net/server/service/MessageService.kt

Added automatic sessionID generation to bgw-net.

---

bgw-net/bgw-net-server/src/main/kotlin/tools/aqua/bgw/net/server/view/MainLayout.kt

Hide "Connections and Sessions" from non-admin users in BGW-net frontend.

---

CHANGELOG.md
bgw-docs/src/main/jekyll/components/uicomponents/uicomponents.md
bgw-examples/bgw-maumau-example/src/main/kotlin/tools/aqua/bgw/examples/maumau/view/scenes/MauMauHostGameMenuScene.kt
bgw-examples/bgw-maumau-example/src/main/kotlin/tools/aqua/bgw/examples/maumau/view/scenes/MauMauJoinGameMenuScene.kt
bgw-gui/src/main/kotlin/tools/aqua/bgw/builder/UINodeBuilder.kt
bgw-gui/src/main/kotlin/tools/aqua/bgw/components/uicomponents/PasswordField.kt
bgw-gui/src/main/kotlin/tools/aqua/bgw/components/uicomponents/TextField.kt

Added PasswordField.

---

CHANGELOG.md
bgw-net/bgw-net-client/src/main/kotlin/tools/aqua/bgw/net/client/BGWWebSocketClient.kt
bgw-net/bgw-net-client/src/main/kotlin/tools/aqua/bgw/net/client/BoardGameClient.kt
bgw-net/bgw-net-common/src/main/kotlin/tools/aqua/bgw/net/common/notification/PlayerJoinedNotification.kt
bgw-net/bgw-net-common/src/main/kotlin/tools/aqua/bgw/net/common/notification/SpectatorJoinedNotification.kt
bgw-net/bgw-net-common/src/main/kotlin/tools/aqua/bgw/net/common/notification/SpectatorLeftNotification.kt
bgw-net/bgw-net-common/src/main/kotlin/tools/aqua/bgw/net/common/request/SpectatorJoinGameMessage.kt
bgw-net/bgw-net-common/src/main/kotlin/tools/aqua/bgw/net/common/response/SpectatorJoinGameResponse.kt
bgw-net/bgw-net-protocol-client/src/main/kotlin/tools/aqua/bgw/net/protocol/client/service/NetworkService.kt
bgw-net/bgw-net-protocol-client/src/main/kotlin/tools/aqua/bgw/net/protocol/client/service/ProtocolBoardGameClient.kt
bgw-net/bgw-net-protocol-client/src/main/kotlin/tools/aqua/bgw/net/protocol/client/view/ConnectionScene.kt
bgw-net/bgw-net-protocol-client/src/main/kotlin/tools/aqua/bgw/net/protocol/client/view/ProtocolClientApplication.kt
bgw-net/bgw-net-protocol-client/src/main/kotlin/tools/aqua/bgw/net/protocol/client/view/messageviews/PlayerJoinedMessageView.kt
bgw-net/bgw-net-server/src/main/kotlin/tools/aqua/bgw/net/server/entity/Player.kt
bgw-net/bgw-net-server/src/main/kotlin/tools/aqua/bgw/net/server/service/MessageService.kt

Spectator join feature

---

CHANGELOG.md
bgw-gui/src/main/kotlin/tools/aqua/bgw/builder/UINodeBuilder.kt

Fixed prompt text displayed twice in ComboBox.

---

README.md
bgw-gui/src/main/kotlin/tools/aqua/bgw/builder/CameraPaneBuilder.kt
bgw-gui/src/main/kotlin/tools/aqua/bgw/builder/ContainerNodeBuilder.kt
bgw-gui/src/main/kotlin/tools/aqua/bgw/builder/FXConverters.kt
bgw-gui/src/main/kotlin/tools/aqua/bgw/builder/HexagonBuilder.kt
bgw-gui/src/main/kotlin/tools/aqua/bgw/builder/NodeBuilder.kt
bgw-gui/src/main/kotlin/tools/aqua/bgw/components/container/HexagonGrid.kt
bgw-gui/src/main/kotlin/tools/aqua/bgw/components/layoutviews/CameraPane.kt
bgw-gui/src/main/kotlin/tools/aqua/bgw/event/MouseEvent.kt
bgw-gui/src/test/kotlin/tools/aqua/bgw/core/FrontendTest.kt
buildSrc/src/main/kotlin/tools/aqua/Repositories.kt

- Updated README for latest upcomming release
- Fixed code style issues for whole project

Streamlined Codebase: README Update and Code Style Refinement

---

CHANGELOG.md
bgw-gui/src/main/kotlin/tools/aqua/bgw/components/ComponentView.kt
bgw-gui/src/main/kotlin/tools/aqua/bgw/components/LayeredContainer.kt
bgw-gui/src/main/kotlin/tools/aqua/bgw/components/RootComponent.kt
bgw-gui/src/main/kotlin/tools/aqua/bgw/components/container/GameComponentContainer.kt
bgw-gui/src/main/kotlin/tools/aqua/bgw/components/layoutviews/Pane.kt
bgw-gui/src/main/kotlin/tools/aqua/bgw/observable/lists/ObservableList.kt
bgw-gui/src/test/kotlin/tools/aqua/bgw/components/LayeredContainerTest.kt
bgw-gui/src/test/kotlin/tools/aqua/bgw/components/uicomponents/structureddataview/StructuredDataViewTestBase.kt
bgw-gui/src/test/kotlin/tools/aqua/bgw/components/uicomponents/structureddataview/listview/ListViewChangeSelectionModeTest.kt
bgw-gui/src/test/kotlin/tools/aqua/bgw/components/uicomponents/structureddataview/listview/ListViewTestBase.kt
bgw-gui/src/test/kotlin/tools/aqua/bgw/components/uicomponents/structureddataview/listview/ListViewTestSelectionModeMultiple.kt
bgw-gui/src/test/kotlin/tools/aqua/bgw/components/uicomponents/structureddataview/listview/ListViewTestSelectionModeNone.kt
bgw-gui/src/test/kotlin/tools/aqua/bgw/components/uicomponents/structureddataview/listview/ListViewTestSelectionModeSingle.kt
bgw-gui/src/test/kotlin/tools/aqua/bgw/components/uicomponents/structureddataview/tableview/TableViewChangeSelectionModeTest.kt
bgw-gui/src/test/kotlin/tools/aqua/bgw/components/uicomponents/structureddataview/tableview/TableViewTestBase.kt
bgw-gui/src/test/kotlin/tools/aqua/bgw/components/uicomponents/structureddataview/tableview/TableViewTestSelectionModeMultiple.kt
bgw-gui/src/test/kotlin/tools/aqua/bgw/components/uicomponents/structureddataview/tableview/TableViewTestSelectionModeNone.kt
bgw-gui/src/test/kotlin/tools/aqua/bgw/components/uicomponents/structureddataview/tableview/TableViewTestSelectionModeSingle.kt
bgw-gui/src/test/kotlin/tools/aqua/bgw/observable/observablelist/SingleListFunctionTests.kt

Set Z layer of ViewComponent within scene without re-adding it to the parent container

---

bgw-gui/src/main/kotlin/tools/aqua/bgw/builder/CameraPaneBuilder.kt

JavaFX boundsInLocal is dynamically calculated. Used bgw internal metrics instead.

[bgw-gui] Fixed CameraPane panning.

---

bgw-gui/src/main/kotlin/tools/aqua/bgw/builder/SceneBuilder.kt

[bgw-gui] Enabled animations for menu scenes

---

bgw-gui/src/main/kotlin/tools/aqua/bgw/util/BidirectionalMap.kt
bgw-gui/src/test/kotlin/tools/aqua/bgw/util/bidirectionalmap/LookupTest.kt
bgw-gui/src/test/kotlin/tools/aqua/bgw/util/bidirectionalmap/OperatorTest.kt
bgw-gui/src/test/kotlin/tools/aqua/bgw/util/bidirectionalmap/PutTest.kt

- Added put and putAll to behave like a normal map in kotlin
- Added get / set operators to behave like a normal map in kotlin with common syntax like map[0] = 5
- Added keysForward / keysBackward / entries to make iterating the map possible in both ways
- Deprecated getDomain() / getCoDomain() in favor of keysForward / keysBackward

[bgw-gui] Added features to BidirectionalMap

---

bgw-examples/bgw-maumau-example/src/main/kotlin/tools/aqua/bgw/examples/maumau/service/network/messages/MauMauEndGameAction.kt
bgw-examples/bgw-maumau-example/src/main/kotlin/tools/aqua/bgw/examples/maumau/service/network/messages/MauMauGameAction.kt
bgw-examples/bgw-maumau-example/src/main/kotlin/tools/aqua/bgw/examples/maumau/service/network/messages/MauMauInitGameAction.kt
bgw-examples/bgw-maumau-example/src/main/kotlin/tools/aqua/bgw/examples/maumau/service/network/messages/MauMauShuffleStackGameAction.kt
bgw-net/bgw-net-common/src/main/kotlin/tools/aqua/bgw/net/common/GameAction.kt
bgw-net/bgw-net-protocol-client/src/main/kotlin/tools/aqua/bgw/net/protocol/client/service/NetworkService.kt

[bgw-net] Enforce toString() in Messages to be implmented

---

CHANGELOG.md
bgw-gui/src/commonMain/kotlin/PropData.kt
bgw-gui/src/jsMain/kotlin/tools/aqua/bgw/Animator.kt
bgw-gui/src/jsMain/kotlin/tools/aqua/bgw/elements/App.kt
bgw-gui/src/jsMain/kotlin/tools/aqua/bgw/elements/container/CardStack.kt
bgw-gui/src/jsMain/kotlin/tools/aqua/bgw/elements/container/HexagonGrid.kt
bgw-gui/src/jsMain/kotlin/tools/aqua/bgw/elements/layoutviews/GridPane.kt
bgw-gui/src/jsMain/kotlin/tools/aqua/bgw/elements/uicomponents/PasswordField.kt
bgw-gui/src/jsMain/kotlin/tools/aqua/bgw/elements/uicomponents/TextArea.kt
bgw-gui/src/jsMain/kotlin/tools/aqua/bgw/elements/uicomponents/TextField.kt
bgw-gui/src/jsMain/kotlin/tools/aqua/bgw/elements/visual/ColorVisual.kt
bgw-gui/src/jsMain/kotlin/tools/aqua/bgw/elements/visual/ImageVisual.kt
bgw-gui/src/jsMain/kotlin/tools/aqua/bgw/elements/visual/TextVisual.kt
bgw-gui/src/jsMain/kotlin/tools/aqua/bgw/event/EventHandlers.kt
bgw-gui/src/jvmMain/kotlin/tools/aqua/bgw/application/JCEFApplication.kt
bgw-gui/src/jvmMain/kotlin/tools/aqua/bgw/components/ComponentView.kt
bgw-gui/src/jvmMain/kotlin/tools/aqua/bgw/components/container/CardStack.kt
bgw-gui/src/jvmMain/kotlin/tools/aqua/bgw/components/container/GameComponentContainer.kt
bgw-gui/src/jvmMain/kotlin/tools/aqua/bgw/components/container/HexagonGrid.kt
bgw-gui/src/jvmMain/kotlin/tools/aqua/bgw/components/container/LinearLayout.kt
bgw-gui/src/jvmMain/kotlin/tools/aqua/bgw/components/layoutviews/GridPane.kt
bgw-gui/src/jvmMain/kotlin/tools/aqua/bgw/mapper/ComponentMapper.kt
bgw-gui/src/jvmMain/kotlin/tools/aqua/bgw/util/ComponentViewGrid.kt
bgw-gui/src/jvmMain/kotlin/tools/aqua/bgw/visual/ColorVisual.kt
bgw-gui/src/jvmMain/kotlin/tools/aqua/bgw/visual/ImageVisual.kt
bgw-gui/src/jvmMain/kotlin/tools/aqua/bgw/visual/SingleLayerVisual.kt
bgw-gui/src/jvmMain/kotlin/tools/aqua/bgw/visual/TextVisual.kt

Closes #414, #415 and #425 .
---
Additinally fixes input lag in TextInputUIComponents caused by repeated UI updates and overhauled the entire positioning system to better work with layouts and containers.

[bgw-gui] Minor quality of life updates and major improvements

---

bgw-net/bgw-net-client/src/main/kotlin/tools/aqua/bgw/net/client/BGWWebSocketClient.kt
bgw-net/bgw-net-common/src/main/kotlin/tools/aqua/bgw/net/common/message/GameActionMessage.kt
bgw-net/bgw-net-common/src/main/kotlin/tools/aqua/bgw/net/common/response/Errors.kt
bgw-net/bgw-net-common/src/main/kotlin/tools/aqua/bgw/net/common/response/GameActionResponse.kt
bgw-net/bgw-net-server/src/main/kotlin/tools/aqua/bgw/net/server/Constants.kt
bgw-net/bgw-net-server/src/main/kotlin/tools/aqua/bgw/net/server/service/MessageService.kt
bgw-net/bgw-net-server/src/main/kotlin/tools/aqua/bgw/net/server/service/validation/JsonSchemaValidator.kt
bgw-net/bgw-net-server/src/main/kotlin/tools/aqua/bgw/net/server/service/validation/ValidationService.kt
bgw-net/bgw-net-server/src/main/resources/bgw_meta_schema.json
bgw-net/bgw-net-server/src/main/resources/docker-compose.yml
bgw-net/bgw-net-server/src/main/resources/maumauschemas/game_action_schema.json
bgw-net/bgw-net-server/src/main/resources/maumauschemas/game_end_schema.json
bgw-net/bgw-net-server/src/main/resources/maumauschemas/game_init_schema.json
bgw-net/bgw-net-server/src/main/resources/maumauschemas/shuffle_stack_schema.json
bgw-net/bgw-net-server/src/main/resources/meta_schema.json

[bgw-net] ValidationService should return map of error and the schema its from to sort the output on the end of the client.
